services:
  - type: web
    name: hotel-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: bash render_build.sh
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: hotel-backend-bpjr.onrender.com
      - key: FRONTEND_ORIGINS
        value: https://hotel-six-theta.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString

databases:
  - name: hotel-db
    plan: free
