services:
  - type: web
    name: hotel-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: hotel-backend.onrender.com
      - key: FRONTEND_ORIGINS
        value: https://your-frontend-domain.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-db
          property: connectionString

databases:
  - name: hotel-db
    plan: free
