services:
  - type: web
    name: hotel-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: bash render_build.sh
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: hotel-backend-bpjr.onrender.com
      - key: FRONTEND_ORIGINS
        value: https://hotel-six-theta.vercel.app
      - key: FRONTEND_ORIGIN_REGEXES
        value: ^https://.*\\.vercel\\.app$
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.vercel.app
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_6PFqwaSpJK8R@ep-divine-lab-aiv27r55-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
